#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("EmotionMusic.Resource", IsApplication=true)]

namespace EmotionMusic
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Microsoft.ProjectOxford.Common.Resource.String.ApplicationName = global::EmotionMusic.Resource.String.ApplicationName;
			global::Microsoft.ProjectOxford.Common.Resource.String.Hello = global::EmotionMusic.Resource.String.Hello;
			global::Microsoft.ProjectOxford.Emotion.Resource.String.ApplicationName = global::EmotionMusic.Resource.String.ApplicationName;
			global::Microsoft.ProjectOxford.Emotion.Resource.String.Hello = global::EmotionMusic.Resource.String.Hello;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int fragment_slide_left_in = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int fragment_slide_left_out = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int fragment_slide_right_in = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int fragment_slide_right_out = 2130968579;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060000
			public const int abc_input_method_navigation_guard = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int abc_search_url_text_normal = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int abc_search_url_text_pressed = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int abc_search_url_text_selected = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int accent_material_dark = 2131099653;
			
			// aapt resource value: 0x7f06011e
			public const int accent_material_light = 2131099934;
			
			// aapt resource value: 0x7f060006
			public const int actionBtnPrs = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int actionbarTabUnselected = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int addToPlayListDialogHeader = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int addToPlayListDisabled = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int addToPlayListNormal = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int allMVShadeViewBackgrandColor = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int atNicknameBg = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int atNicknameFg = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int background_floating_material_dark = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int background_floating_material_light = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int background_material_dark = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int background_material_light = 2131099665;
			
			// aapt resource value: 0x7f06011b
			public const int baiyan = 2131099931;
			
			// aapt resource value: 0x7f060001
			public const int black = 2131099649;
			
			// aapt resource value: 0x7f060012
			public const int blue = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int bottomSheetNormalBackground = 2131099667;
			
			// aapt resource value: 0x7f060014
			public const int bottomSheetNormalBackgroundNight = 2131099668;
			
			// aapt resource value: 0x7f060015
			public const int bottomSheetNormalBackgroundPress = 2131099669;
			
			// aapt resource value: 0x7f060016
			public const int bottomSheetNormalBackgroundPressNight = 2131099670;
			
			// aapt resource value: 0x7f060017
			public const int bright_foreground_disabled_material_dark = 2131099671;
			
			// aapt resource value: 0x7f060018
			public const int bright_foreground_disabled_material_light = 2131099672;
			
			// aapt resource value: 0x7f060019
			public const int bright_foreground_inverse_material_dark = 2131099673;
			
			// aapt resource value: 0x7f06001a
			public const int bright_foreground_inverse_material_light = 2131099674;
			
			// aapt resource value: 0x7f06001b
			public const int bright_foreground_material_dark = 2131099675;
			
			// aapt resource value: 0x7f06001c
			public const int bright_foreground_material_light = 2131099676;
			
			// aapt resource value: 0x7f06001d
			public const int bs_dark_divider_color = 2131099677;
			
			// aapt resource value: 0x7f06001e
			public const int bs_divider_color = 2131099678;
			
			// aapt resource value: 0x7f06001f
			public const int bubbleBg = 2131099679;
			
			// aapt resource value: 0x7f060020
			public const int buttonPressedTextColor = 2131099680;
			
			// aapt resource value: 0x7f060021
			public const int buttonTextColor = 2131099681;
			
			// aapt resource value: 0x7f060022
			public const int button_material_dark = 2131099682;
			
			// aapt resource value: 0x7f060023
			public const int button_material_light = 2131099683;
			
			// aapt resource value: 0x7f060024
			public const int chatBarEditHintTextColor = 2131099684;
			
			// aapt resource value: 0x7f060025
			public const int chatBarEditTextColor = 2131099685;
			
			// aapt resource value: 0x7f060026
			public const int chatBarLineColor = 2131099686;
			
			// aapt resource value: 0x7f060027
			public const int chatBarPostDisableTextColor = 2131099687;
			
			// aapt resource value: 0x7f060028
			public const int chatBarPostTextColor = 2131099688;
			
			// aapt resource value: 0x7f060029
			public const int commentBarEditHintTextColor = 2131099689;
			
			// aapt resource value: 0x7f06002a
			public const int commentBarEditTextColor = 2131099690;
			
			// aapt resource value: 0x7f06002b
			public const int commentBarLineColor = 2131099691;
			
			// aapt resource value: 0x7f06002c
			public const int commentBarPostDisableTextColor = 2131099692;
			
			// aapt resource value: 0x7f06002d
			public const int commentBarPostTextColor = 2131099693;
			
			// aapt resource value: 0x7f06002e
			public const int contentTvColor = 2131099694;
			
			// aapt resource value: 0x7f06002f
			public const int creamPlaylistChooseClassTitleColor = 2131099695;
			
			// aapt resource value: 0x7f060030
			public const int creamPlaylistEntranceHeaderBackground = 2131099696;
			
			// aapt resource value: 0x7f060031
			public const int creamPlaylistEntranceSubTitleColor = 2131099697;
			
			// aapt resource value: 0x7f060032
			public const int creamPlaylistEntranceTitleColor = 2131099698;
			
			// aapt resource value: 0x7f060033
			public const int design_fab_shadow_end_color = 2131099699;
			
			// aapt resource value: 0x7f060034
			public const int design_fab_shadow_mid_color = 2131099700;
			
			// aapt resource value: 0x7f060035
			public const int design_fab_shadow_start_color = 2131099701;
			
			// aapt resource value: 0x7f060036
			public const int design_fab_stroke_end_inner_color = 2131099702;
			
			// aapt resource value: 0x7f060037
			public const int design_fab_stroke_end_outer_color = 2131099703;
			
			// aapt resource value: 0x7f060038
			public const int design_fab_stroke_top_inner_color = 2131099704;
			
			// aapt resource value: 0x7f060039
			public const int design_fab_stroke_top_outer_color = 2131099705;
			
			// aapt resource value: 0x7f06003a
			public const int design_snackbar_background_color = 2131099706;
			
			// aapt resource value: 0x7f06003b
			public const int design_textinput_error_color = 2131099707;
			
			// aapt resource value: 0x7f06003c
			public const int dim_foreground_disabled_material_dark = 2131099708;
			
			// aapt resource value: 0x7f06003d
			public const int dim_foreground_disabled_material_light = 2131099709;
			
			// aapt resource value: 0x7f06003e
			public const int dim_foreground_material_dark = 2131099710;
			
			// aapt resource value: 0x7f06003f
			public const int dim_foreground_material_light = 2131099711;
			
			// aapt resource value: 0x7f060040
			public const int disableColor = 2131099712;
			
			// aapt resource value: 0x7f060041
			public const int dotFocusColor = 2131099713;
			
			// aapt resource value: 0x7f060042
			public const int dotNormalColor = 2131099714;
			
			// aapt resource value: 0x7f060043
			public const int dotNormalNightColor = 2131099715;
			
			// aapt resource value: 0x7f060044
			public const int drawerNightBg = 2131099716;
			
			// aapt resource value: 0x7f060045
			public const int emotionDotFocusColor = 2131099717;
			
			// aapt resource value: 0x7f060046
			public const int emotionDotNormalColor = 2131099718;
			
			// aapt resource value: 0x7f060047
			public const int flipColor = 2131099719;
			
			// aapt resource value: 0x7f060048
			public const int floatLrc00030Bg = 2131099720;
			
			// aapt resource value: 0x7f060049
			public const int floatLrcfff20Bg = 2131099721;
			
			// aapt resource value: 0x7f06004a
			public const int foreground_material_dark = 2131099722;
			
			// aapt resource value: 0x7f06004b
			public const int foreground_material_light = 2131099723;
			
			// aapt resource value: 0x7f06004c
			public const int headerImageCover = 2131099724;
			
			// aapt resource value: 0x7f06004d
			public const int highlighted_text_material_dark = 2131099725;
			
			// aapt resource value: 0x7f06004e
			public const int highlighted_text_material_light = 2131099726;
			
			// aapt resource value: 0x7f06004f
			public const int hint_foreground_material_dark = 2131099727;
			
			// aapt resource value: 0x7f060050
			public const int hint_foreground_material_light = 2131099728;
			
			// aapt resource value: 0x7f060051
			public const int inputTextColor = 2131099729;
			
			// aapt resource value: 0x7f060052
			public const int inputTextHintColor = 2131099730;
			
			// aapt resource value: 0x7f060053
			public const int introduceBg = 2131099731;
			
			// aapt resource value: 0x7f060054
			public const int invalidAlarmClockBellAndRepeat = 2131099732;
			
			// aapt resource value: 0x7f060055
			public const int invalidAlarmClockBellAndRepeatNight = 2131099733;
			
			// aapt resource value: 0x7f060056
			public const int invalidAlarmClockSongName = 2131099734;
			
			// aapt resource value: 0x7f060057
			public const int invalidAlarmClockSongNameNight = 2131099735;
			
			// aapt resource value: 0x7f060058
			public const int invalidAlarmClockTime = 2131099736;
			
			// aapt resource value: 0x7f060059
			public const int invalidAlarmClockTimeNight = 2131099737;
			
			// aapt resource value: 0x7f06005a
			public const int lineColor = 2131099738;
			
			// aapt resource value: 0x7f06005b
			public const int listDivider = 2131099739;
			
			// aapt resource value: 0x7f06005c
			public const int listDividerColor = 2131099740;
			
			// aapt resource value: 0x7f06005d
			public const int listHeavyDividerColor = 2131099741;
			
			// aapt resource value: 0x7f06005e
			public const int listItemNightColorWhite = 2131099742;
			
			// aapt resource value: 0x7f06005f
			public const int listItemPressedColor = 2131099743;
			
			// aapt resource value: 0x7f060060
			public const int listItemPressedColorWhite = 2131099744;
			
			// aapt resource value: 0x7f060061
			public const int listItemPressedNightColor = 2131099745;
			
			// aapt resource value: 0x7f060062
			public const int listItemPressedNightColorWhite = 2131099746;
			
			// aapt resource value: 0x7f060063
			public const int listSubTextColor = 2131099747;
			
			// aapt resource value: 0x7f060064
			public const int listTextColor = 2131099748;
			
			// aapt resource value: 0x7f060065
			public const int listTitleBackground = 2131099749;
			
			// aapt resource value: 0x7f060066
			public const int listTitleDivider = 2131099750;
			
			// aapt resource value: 0x7f060067
			public const int liveHeadColor = 2131099751;
			
			// aapt resource value: 0x7f060068
			public const int liveIntroduceColor = 2131099752;
			
			// aapt resource value: 0x7f060069
			public const int liveMeColor = 2131099753;
			
			// aapt resource value: 0x7f06006a
			public const int liveRankGrey = 2131099754;
			
			// aapt resource value: 0x7f06006b
			public const int liveRankYellow = 2131099755;
			
			// aapt resource value: 0x7f06006c
			public const int localImageBrowseActionbarColor = 2131099756;
			
			// aapt resource value: 0x7f06006d
			public const int lrcAdjustListPrs = 2131099757;
			
			// aapt resource value: 0x7f06006e
			public const int lrcHighLight = 2131099758;
			
			// aapt resource value: 0x7f06006f
			public const int lrcNormal = 2131099759;
			
			// aapt resource value: 0x7f060070
			public const int lrcOverLight = 2131099760;
			
			// aapt resource value: 0x7f060071
			public const int lrcShareColor = 2131099761;
			
			// aapt resource value: 0x7f060072
			public const int lrcShareListBg = 2131099762;
			
			// aapt resource value: 0x7f060073
			public const int lrcShareSaveAndShareNormalColor = 2131099763;
			
			// aapt resource value: 0x7f060074
			public const int lrcShareSaveAndSharePressedColor = 2131099764;
			
			// aapt resource value: 0x7f060075
			public const int lrcShareTextnormalColor = 2131099765;
			
			// aapt resource value: 0x7f060076
			public const int mainDrawerHeaderMask = 2131099766;
			
			// aapt resource value: 0x7f060077
			public const int mainRadioBillboardHeaderPreEntranceForeground = 2131099767;
			
			// aapt resource value: 0x7f060078
			public const int mainTextColor = 2131099768;
			
			// aapt resource value: 0x7f060079
			public const int mainTextSongInfoColor = 2131099769;
			
			// aapt resource value: 0x7f06007a
			public const int material_blue_grey_800 = 2131099770;
			
			// aapt resource value: 0x7f06007b
			public const int material_blue_grey_900 = 2131099771;
			
			// aapt resource value: 0x7f06007c
			public const int material_blue_grey_950 = 2131099772;
			
			// aapt resource value: 0x7f06007d
			public const int material_deep_teal_200 = 2131099773;
			
			// aapt resource value: 0x7f06007e
			public const int material_deep_teal_500 = 2131099774;
			
			// aapt resource value: 0x7f06007f
			public const int material_grey_100 = 2131099775;
			
			// aapt resource value: 0x7f060080
			public const int material_grey_300 = 2131099776;
			
			// aapt resource value: 0x7f060081
			public const int material_grey_50 = 2131099777;
			
			// aapt resource value: 0x7f060082
			public const int material_grey_600 = 2131099778;
			
			// aapt resource value: 0x7f060083
			public const int material_grey_800 = 2131099779;
			
			// aapt resource value: 0x7f060084
			public const int material_grey_850 = 2131099780;
			
			// aapt resource value: 0x7f060085
			public const int material_grey_900 = 2131099781;
			
			// aapt resource value: 0x7f060086
			public const int md_btn_selected = 2131099782;
			
			// aapt resource value: 0x7f060087
			public const int md_btn_selected_dark = 2131099783;
			
			// aapt resource value: 0x7f060088
			public const int md_divider_black = 2131099784;
			
			// aapt resource value: 0x7f060089
			public const int md_divider_white = 2131099785;
			
			// aapt resource value: 0x7f06008a
			public const int md_edittext_error = 2131099786;
			
			// aapt resource value: 0x7f06008b
			public const int md_material_blue_600 = 2131099787;
			
			// aapt resource value: 0x7f06008c
			public const int md_material_blue_800 = 2131099788;
			
			// aapt resource value: 0x7f06008d
			public const int md_material_btn_blue = 2131099789;
			
			// aapt resource value: 0x7f06008e
			public const int menuPressed = 2131099790;
			
			// aapt resource value: 0x7f06008f
			public const int minPlayerBtnPrs = 2131099791;
			
			// aapt resource value: 0x7f060090
			public const int minorTextColor = 2131099792;
			
			// aapt resource value: 0x7f060091
			public const int minorTextColor2 = 2131099793;
			
			// aapt resource value: 0x7f060092
			public const int moreBvTextColor = 2131099794;
			
			// aapt resource value: 0x7f060093
			public const int musicTransName = 2131099795;
			
			// aapt resource value: 0x7f060094
			public const int mvBarBg = 2131099796;
			
			// aapt resource value: 0x7f060095
			public const int mvQualityNormal = 2131099797;
			
			// aapt resource value: 0x7f060096
			public const int mvQualitySelected = 2131099798;
			
			// aapt resource value: 0x7f060097
			public const int nightLine = 2131099799;
			
			// aapt resource value: 0x7f060098
			public const int nightLineBottomSheet = 2131099800;
			
			// aapt resource value: 0x7f060099
			public const int nightLineColor = 2131099801;
			
			// aapt resource value: 0x7f06009a
			public const int nightNormalBackground = 2131099802;
			
			// aapt resource value: 0x7f06009b
			public const int nightPressed = 2131099803;
			
			// aapt resource value: 0x7f06009c
			public const int nightPressedCombine = 2131099804;
			
			// aapt resource value: 0x7f06009d
			public const int nightY0 = 2131099805;
			
			// aapt resource value: 0x7f06009e
			public const int nightY1 = 2131099806;
			
			// aapt resource value: 0x7f06009f
			public const int nightY10 = 2131099807;
			
			// aapt resource value: 0x7f0600a0
			public const int nightY11 = 2131099808;
			
			// aapt resource value: 0x7f0600a1
			public const int nightY13 = 2131099809;
			
			// aapt resource value: 0x7f0600a2
			public const int nightY2 = 2131099810;
			
			// aapt resource value: 0x7f0600a3
			public const int nightY3 = 2131099811;
			
			// aapt resource value: 0x7f0600a4
			public const int nightY4 = 2131099812;
			
			// aapt resource value: 0x7f0600a5
			public const int nightY4_4c = 2131099813;
			
			// aapt resource value: 0x7f0600a6
			public const int nightY5 = 2131099814;
			
			// aapt resource value: 0x7f0600a7
			public const int nightY50001 = 2131099815;
			
			// aapt resource value: 0x7f0600a8
			public const int nightY6 = 2131099816;
			
			// aapt resource value: 0x7f0600a9
			public const int nightY7 = 2131099817;
			
			// aapt resource value: 0x7f0600aa
			public const int nightY70001 = 2131099818;
			
			// aapt resource value: 0x7f0600ab
			public const int nightY8 = 2131099819;
			
			// aapt resource value: 0x7f0600ac
			public const int nightY9 = 2131099820;
			
			// aapt resource value: 0x7f0600ad
			public const int nightYa = 2131099821;
			
			// aapt resource value: 0x7f0600ae
			public const int normalBackground = 2131099822;
			
			// aapt resource value: 0x7f0600af
			public const int normalBackground2 = 2131099823;
			
			// aapt resource value: 0x7f0600b0
			public const int normalC1 = 2131099824;
			
			// aapt resource value: 0x7f0600b1
			public const int normalC10 = 2131099825;
			
			// aapt resource value: 0x7f0600b2
			public const int normalC2 = 2131099826;
			
			// aapt resource value: 0x7f0600b3
			public const int normalC3 = 2131099827;
			
			// aapt resource value: 0x7f0600b4
			public const int normalC3_4c = 2131099828;
			
			// aapt resource value: 0x7f0600b5
			public const int normalC4 = 2131099829;
			
			// aapt resource value: 0x7f0600b6
			public const int normalC5 = 2131099830;
			
			// aapt resource value: 0x7f0600b7
			public const int normalC6 = 2131099831;
			
			// aapt resource value: 0x7f0600b8
			public const int normalC7 = 2131099832;
			
			// aapt resource value: 0x7f0600b9
			public const int normalC9 = 2131099833;
			
			// aapt resource value: 0x7f0600ba
			public const int normalCa = 2131099834;
			
			// aapt resource value: 0x7f0600bb
			public const int normalColor = 2131099835;
			
			// aapt resource value: 0x7f0600bc
			public const int notification_bg = 2131099836;
			
			// aapt resource value: 0x7f0600bd
			public const int notification_content = 2131099837;
			
			// aapt resource value: 0x7f0600be
			public const int notification_title = 2131099838;
			
			// aapt resource value: 0x7f0600bf
			public const int playbarProgressColor = 2131099839;
			
			// aapt resource value: 0x7f0600c0
			public const int playbarSubTextColor = 2131099840;
			
			// aapt resource value: 0x7f0600c1
			public const int playbarTextColor = 2131099841;
			
			// aapt resource value: 0x7f0600c2
			public const int playerDropMenuBgPrs = 2131099842;
			
			// aapt resource value: 0x7f0600c3
			public const int playerLyricBg = 2131099843;
			
			// aapt resource value: 0x7f0600c4
			public const int playlistDefaultBackgound = 2131099844;
			
			// aapt resource value: 0x7f0600c5
			public const int playlistDetailMask = 2131099845;
			
			// aapt resource value: 0x7f0600c6
			public const int playlistDetailMaskNight = 2131099846;
			
			// aapt resource value: 0x7f0600c7
			public const int playlistDetailPlaceholder = 2131099847;
			
			// aapt resource value: 0x7f0600c8
			public const int pmsgSendBtnDisable = 2131099848;
			
			// aapt resource value: 0x7f0600c9
			public const int pmsgSendBtnEnable = 2131099849;
			
			// aapt resource value: 0x7f0600ca
			public const int pressedColor = 2131099850;
			
			// aapt resource value: 0x7f0600cb
			public const int pressedWhiteColo2 = 2131099851;
			
			// aapt resource value: 0x7f0600cc
			public const int pressedWhiteColor = 2131099852;
			
			// aapt resource value: 0x7f0600cd
			public const int primary_dark_material_dark = 2131099853;
			
			// aapt resource value: 0x7f0600ce
			public const int primary_dark_material_light = 2131099854;
			
			// aapt resource value: 0x7f0600cf
			public const int primary_material_dark = 2131099855;
			
			// aapt resource value: 0x7f0600d0
			public const int primary_material_light = 2131099856;
			
			// aapt resource value: 0x7f0600d1
			public const int primary_text_default_material_dark = 2131099857;
			
			// aapt resource value: 0x7f0600d2
			public const int primary_text_default_material_light = 2131099858;
			
			// aapt resource value: 0x7f0600d3
			public const int primary_text_disabled_material_dark = 2131099859;
			
			// aapt resource value: 0x7f0600d4
			public const int primary_text_disabled_material_light = 2131099860;
			
			// aapt resource value: 0x7f0600d5
			public const int profileDotFocusColor = 2131099861;
			
			// aapt resource value: 0x7f0600d6
			public const int profileDotNormalColor = 2131099862;
			
			// aapt resource value: 0x7f0600d7
			public const int profileInfoTextColor = 2131099863;
			
			// aapt resource value: 0x7f06011a
			public const int qianhuise = 2131099930;
			
			// aapt resource value: 0x7f0600d8
			public const int radioBillboardHeaderBackgroundBoxColor = 2131099864;
			
			// aapt resource value: 0x7f0600d9
			public const int radioBillboardHeaderBackgroundPressedColor = 2131099865;
			
			// aapt resource value: 0x7f0600da
			public const int radioPlayerBg = 2131099866;
			
			// aapt resource value: 0x7f0600db
			public const int rankNumNomalColor = 2131099867;
			
			// aapt resource value: 0x7f0600dc
			public const int rankNumTopThreeColor = 2131099868;
			
			// aapt resource value: 0x7f0600dd
			public const int recordProgramCaching = 2131099869;
			
			// aapt resource value: 0x7f0600de
			public const int recordProgramCachingNight = 2131099870;
			
			// aapt resource value: 0x7f0600df
			public const int recordProgramProcess = 2131099871;
			
			// aapt resource value: 0x7f0600e0
			public const int recordProgramProcessNight = 2131099872;
			
			// aapt resource value: 0x7f0600e1
			public const int redTagColor = 2131099873;
			
			// aapt resource value: 0x7f0600e2
			public const int resendPressedNightTextColor = 2131099874;
			
			// aapt resource value: 0x7f0600e3
			public const int resendPressedTextColor = 2131099875;
			
			// aapt resource value: 0x7f0600e4
			public const int resendTextColor = 2131099876;
			
			// aapt resource value: 0x7f0600e5
			public const int ripple_material_dark = 2131099877;
			
			// aapt resource value: 0x7f0600e6
			public const int ripple_material_light = 2131099878;
			
			// aapt resource value: 0x7f0600e7
			public const int searchHighlight = 2131099879;
			
			// aapt resource value: 0x7f060119
			public const int search_bg = 2131099929;
			
			// aapt resource value: 0x7f0600e8
			public const int secondary_text_default_material_dark = 2131099880;
			
			// aapt resource value: 0x7f0600e9
			public const int secondary_text_default_material_light = 2131099881;
			
			// aapt resource value: 0x7f0600ea
			public const int secondary_text_disabled_material_dark = 2131099882;
			
			// aapt resource value: 0x7f0600eb
			public const int secondary_text_disabled_material_light = 2131099883;
			
			// aapt resource value: 0x7f060118
			public const int smallRed = 2131099928;
			
			// aapt resource value: 0x7f0600ec
			public const int sportFMMask1 = 2131099884;
			
			// aapt resource value: 0x7f0600ed
			public const int sportFMMask2 = 2131099885;
			
			// aapt resource value: 0x7f0600ee
			public const int sportRadioShareTextColor = 2131099886;
			
			// aapt resource value: 0x7f0600ef
			public const int statusBarPress = 2131099887;
			
			// aapt resource value: 0x7f0600f0
			public const int statusBarPressVivo = 2131099888;
			
			// aapt resource value: 0x7f0600f1
			public const int statusBarTranslucent = 2131099889;
			
			// aapt resource value: 0x7f06011d
			public const int status_bar = 2131099933;
			
			// aapt resource value: 0x7f0600f2
			public const int switch_thumb_disabled_material_dark = 2131099890;
			
			// aapt resource value: 0x7f0600f3
			public const int switch_thumb_disabled_material_light = 2131099891;
			
			// aapt resource value: 0x7f0600f4
			public const int switch_thumb_normal_material_dark = 2131099892;
			
			// aapt resource value: 0x7f0600f5
			public const int switch_thumb_normal_material_light = 2131099893;
			
			// aapt resource value: 0x7f0600f6
			public const int tabColor = 2131099894;
			
			// aapt resource value: 0x7f0600f7
			public const int tabShadow = 2131099895;
			
			// aapt resource value: 0x7f0600f8
			public const int tabTextNormalColor = 2131099896;
			
			// aapt resource value: 0x7f0600f9
			public const int tagTextColor = 2131099897;
			
			// aapt resource value: 0x7f0600fa
			public const int themeColor = 2131099898;
			
			// aapt resource value: 0x7f0600fb
			public const int theme_color_Primary = 2131099899;
			
			// aapt resource value: 0x7f0600fc
			public const int theme_color_PrimaryAccent = 2131099900;
			
			// aapt resource value: 0x7f0600fd
			public const int theme_color_PrimaryDark = 2131099901;
			
			// aapt resource value: 0x7f0600fe
			public const int theme_color_c2_common_bg = 2131099902;
			
			// aapt resource value: 0x7f0600ff
			public const int theme_color_c3_333 = 2131099903;
			
			// aapt resource value: 0x7f060100
			public const int theme_color_c4_666 = 2131099904;
			
			// aapt resource value: 0x7f060101
			public const int theme_color_c5_888 = 2131099905;
			
			// aapt resource value: 0x7f060102
			public const int theme_color_c6_999 = 2131099906;
			
			// aapt resource value: 0x7f060103
			public const int theme_color_c7_b2 = 2131099907;
			
			// aapt resource value: 0x7f060104
			public const int theme_color_c8_ccc = 2131099908;
			
			// aapt resource value: 0x7f060105
			public const int theme_color_c9_blue = 2131099909;
			
			// aapt resource value: 0x7f060106
			public const int theme_color_ca_fff = 2131099910;
			
			// aapt resource value: 0x7f060107
			public const int theme_color_common_section = 2131099911;
			
			// aapt resource value: 0x7f060108
			public const int theme_color_cover_dark = 2131099912;
			
			// aapt resource value: 0x7f060109
			public const int theme_color_fff = 2131099913;
			
			// aapt resource value: 0x7f06010a
			public const int theme_color_forcard = 2131099914;
			
			// aapt resource value: 0x7f06010b
			public const int theme_color_forcard_night = 2131099915;
			
			// aapt resource value: 0x7f06010c
			public const int theme_ripple_dark = 2131099916;
			
			// aapt resource value: 0x7f06010d
			public const int theme_ripple_light = 2131099917;
			
			// aapt resource value: 0x7f06010e
			public const int theme_ripple_mask_dark = 2131099918;
			
			// aapt resource value: 0x7f06010f
			public const int theme_ripple_mask_light = 2131099919;
			
			// aapt resource value: 0x7f060110
			public const int toolbarIconColor = 2131099920;
			
			// aapt resource value: 0x7f060111
			public const int toolbarSubTextColor = 2131099921;
			
			// aapt resource value: 0x7f060112
			public const int toolbarTextColor = 2131099922;
			
			// aapt resource value: 0x7f060113
			public const int trackContentContainerNormalBg = 2131099923;
			
			// aapt resource value: 0x7f060114
			public const int trackContentContainerPressBg = 2131099924;
			
			// aapt resource value: 0x7f060115
			public const int videoWindowBg = 2131099925;
			
			// aapt resource value: 0x7f060116
			public const int videoWindowBgPrs = 2131099926;
			
			// aapt resource value: 0x7f06011c
			public const int whaite_text = 2131099932;
			
			// aapt resource value: 0x7f060117
			public const int white = 2131099927;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int anger = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int back = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int back12 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int back2G = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int back3 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Button1 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int CameraButton = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int CameraButton1 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int CameraButton2 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int contempt = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int DefaultUser = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int disgust = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int fare = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int happiness = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int Icon = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int ItemAsButton = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int MainIcon = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int MineButton = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int MusicButton1 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int MusicButton1_2 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int MusicButton2 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int MusicButton2_2 = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int neutral = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int onpu = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int onpu2 = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int RecommendButton = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int sadness = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int SettingButton = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int SettingButton1 = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int SettingButton2 = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int surprise = 2130837534;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080005
			public const int LoginLayout_LoginButton = 2131230725;
			
			// aapt resource value: 0x7f080004
			public const int LoginLayout_Password = 2131230724;
			
			// aapt resource value: 0x7f080003
			public const int LoginLayout_Username = 2131230723;
			
			// aapt resource value: 0x7f080006
			public const int MainFragment_RecommendMusicListView = 2131230726;
			
			// aapt resource value: 0x7f080015
			public const int MainLayout_Body = 2131230741;
			
			// aapt resource value: 0x7f080009
			public const int MainLayout_Foot = 2131230729;
			
			// aapt resource value: 0x7f08000a
			public const int MainLayout_Foot_NextButton = 2131230730;
			
			// aapt resource value: 0x7f08000c
			public const int MainLayout_Foot_Previous = 2131230732;
			
			// aapt resource value: 0x7f08000d
			public const int MainLayout_Foot_Text1 = 2131230733;
			
			// aapt resource value: 0x7f08000e
			public const int MainLayout_Foot_Text2 = 2131230734;
			
			// aapt resource value: 0x7f08000b
			public const int MainLayout_PlayButton = 2131230731;
			
			// aapt resource value: 0x7f080011
			public const int MainLayout_RadioButton0 = 2131230737;
			
			// aapt resource value: 0x7f080012
			public const int MainLayout_RadioButton1 = 2131230738;
			
			// aapt resource value: 0x7f080013
			public const int MainLayout_RadioButton2 = 2131230739;
			
			// aapt resource value: 0x7f080014
			public const int MainLayout_RadioButton3 = 2131230740;
			
			// aapt resource value: 0x7f080010
			public const int MainLayout_RadioGroup = 2131230736;
			
			// aapt resource value: 0x7f08000f
			public const int MainLayout_Toolbar = 2131230735;
			
			// aapt resource value: 0x7f080007
			public const int MainLayout_Top = 2131230727;
			
			// aapt resource value: 0x7f080008
			public const int MainLayout_TopText = 2131230728;
			
			// aapt resource value: 0x7f080017
			public const int MineFragment_MineListView = 2131230743;
			
			// aapt resource value: 0x7f08002a
			public const int PlayLayout2_Foot = 2131230762;
			
			// aapt resource value: 0x7f08002d
			public const int PlayLayout2_Foot_NextButton = 2131230765;
			
			// aapt resource value: 0x7f08002c
			public const int PlayLayout2_Foot_PlayButton = 2131230764;
			
			// aapt resource value: 0x7f08002b
			public const int PlayLayout2_Foot_Previous = 2131230763;
			
			// aapt resource value: 0x7f080027
			public const int PlayLayout2_Image = 2131230759;
			
			// aapt resource value: 0x7f080028
			public const int PlayLayout2_LrcBackground = 2131230760;
			
			// aapt resource value: 0x7f080029
			public const int PlayLayout2_LrcText = 2131230761;
			
			// aapt resource value: 0x7f080023
			public const int PlayLayout2_PlayBackground = 2131230755;
			
			// aapt resource value: 0x7f080024
			public const int PlayLayout2_Top = 2131230756;
			
			// aapt resource value: 0x7f080025
			public const int PlayLayout2_Top_BackButton = 2131230757;
			
			// aapt resource value: 0x7f080026
			public const int PlayLayout2_Top_Text = 2131230758;
			
			// aapt resource value: 0x7f08001f
			public const int PlayLayout_Foot = 2131230751;
			
			// aapt resource value: 0x7f080022
			public const int PlayLayout_Foot_NextButton = 2131230754;
			
			// aapt resource value: 0x7f080021
			public const int PlayLayout_Foot_PlayButton = 2131230753;
			
			// aapt resource value: 0x7f080020
			public const int PlayLayout_Foot_Previous = 2131230752;
			
			// aapt resource value: 0x7f08001c
			public const int PlayLayout_Image = 2131230748;
			
			// aapt resource value: 0x7f08001d
			public const int PlayLayout_LrcBackground = 2131230749;
			
			// aapt resource value: 0x7f08001e
			public const int PlayLayout_LrcText = 2131230750;
			
			// aapt resource value: 0x7f080018
			public const int PlayLayout_PlayBackground = 2131230744;
			
			// aapt resource value: 0x7f080019
			public const int PlayLayout_Top = 2131230745;
			
			// aapt resource value: 0x7f08001a
			public const int PlayLayout_Top_BackButton = 2131230746;
			
			// aapt resource value: 0x7f08001b
			public const int PlayLayout_Top_Text = 2131230747;
			
			// aapt resource value: 0x7f080032
			public const int SettingFragment_LogoutButton = 2131230770;
			
			// aapt resource value: 0x7f08002f
			public const int SettingFragment_UserAccount = 2131230767;
			
			// aapt resource value: 0x7f080030
			public const int SettingFragment_UserImage = 2131230768;
			
			// aapt resource value: 0x7f080031
			public const int SettingFragment_Username = 2131230769;
			
			// aapt resource value: 0x7f080000
			public const int content = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int handle = 2131230721;
			
			// aapt resource value: 0x7f080016
			public const int linearLayout1 = 2131230742;
			
			// aapt resource value: 0x7f080002
			public const int slidingDrawer1 = 2131230722;
			
			// aapt resource value: 0x7f08002e
			public const int textView1 = 2131230766;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Drawer = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int LoginLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int MainFragment = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int MainLayout_Relative = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int MineFragment = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int MyMusicListLayout = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int PlayLayout = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int PlayLayout2 = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int RecommendMusic = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int SettingFragment = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Start = 2130903050;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050005
			public const int Login = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int LoginFailed = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int Logout = 2131034119;
			
			// aapt resource value: 0x7f050004
			public const int Password = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int SkinColor = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int Username = 2131034115;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int AppTheme = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int Night = 2131165185;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
